<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-FFP2A00" failures="2" tests="2" name="Test(failed)" time="29.299" errors="0" timestamp="2023-02-18T19:27:04 EST">
  <testcase classname="testCases.TC_002_LoginTest" name="test_Login" time="21.071">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_002_LoginTest.test_Login(TC_002_LoginTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test_Login -->
  <testcase classname="testCases.TC_003_LoginDataDrivenTest" name="test_LoginDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: \testData\Opencart_LoginData.xlsx (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: \testData\Opencart_LoginData.xlsx (The system cannot find the path specified)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.io.FileNotFoundException: \testData\Opencart_LoginData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at utilities.ExcelUtility.getRowCount(ExcelUtility.java:37)
at utilities.DataProviders.getData(DataProviders.java:15)
... 25 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test_LoginDDT -->
</testsuite> <!-- Test(failed) -->
